apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "gitlab-runner.fullname" . }}
  name: gitlab-runner-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-disk
status: {}
